export const ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_ENVIRONMENT: 'INVALID_ENVIRONMENT',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  INVALID_AGENT_INPUT: 'INVALID_AGENT_INPUT',
  INVALID_AGENT_OUTPUT: 'INVALID_AGENT_OUTPUT',
  INVALID_ARTIFACT: 'INVALID_ARTIFACT',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  PERSISTENCE_CONFLICT: 'PERSISTENCE_CONFLICT',
  PERSISTENCE_ERROR: 'PERSISTENCE_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
