import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    fileParallelism: false,
    hookTimeout: 60_000,
    testTimeout: 60_000,
    include: [
      'agents/developer/**/*.spec.ts',
      'agents/product-owner/**/*.spec.ts',
      'agents/qa/**/*.spec.ts',
      'core/agent-runner/**/*.spec.ts',
      'core/ai-provider/**/*.spec.ts',
      'core/artifact-generator/**/*.spec.ts',
      'core/execution-engine/**/*.spec.ts',
      'core/knowledge-loader/**/*.spec.ts',
      'core/orchestrator/**/*.spec.ts',
      'core/prompt-builder/**/*.spec.ts',
      'core/response-validator/**/*.spec.ts',
      'shared/**/*.spec.ts',
      'prisma/**/*.spec.ts',
    ],
    exclude: ['core/ai-provider/**/*.live.spec.ts'],
    coverage: {
      provider: 'v8',
      include: [
        'agents/developer/**/*.ts',
        'agents/product-owner/**/*.ts',
        'agents/qa/**/*.ts',
        'core/agent-runner/**/*.ts',
        'core/ai-provider/**/*.ts',
        'core/artifact-generator/**/*.ts',
        'core/execution-engine/**/*.ts',
        'core/knowledge-loader/**/*.ts',
        'core/orchestrator/**/*.ts',
        'core/prompt-builder/**/*.ts',
        'core/response-validator/**/*.ts',
        'shared/**/*.ts',
        'prisma/**/*.ts',
      ],
      exclude: [
        '**/*.spec.ts',
        'agents/developer/testing/**',
        'agents/product-owner/testing/**',
        'agents/qa/testing/**',
        'core/orchestrator/testing/**',
        'core/execution-engine/testing/**',
        'shared/types/**',
        'generated/**',
      ],
      reporter: ['text', 'json-summary'],
    },
  },
});
