import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    fileParallelism: false,
    hookTimeout: 60_000,
    testTimeout: 60_000,
    include: [
      'agents/code-generator/**/*.spec.ts',
      'agents/developer/**/*.spec.ts',
      'agents/product-owner/**/*.spec.ts',
      'agents/qa/**/*.spec.ts',
      'core/adaptive-orchestrator/**/*.spec.ts',
      'core/agent-runner/**/*.spec.ts',
      'core/ai-provider/**/*.spec.ts',
      'core/artifact-generator/**/*.spec.ts',
      'core/agent-contract-invariants/**/*.spec.ts',
      'core/controlled-workspace/**/*.spec.ts',
      'core/factory-execution-profile/**/*.spec.ts',
      'core/sandbox-runner/**/*.spec.ts',
      'core/factory-pipeline/**/*.spec.ts',
      'core/execution-engine/**/*.spec.ts',
      'core/execution-repository/**/*.spec.ts',
      'core/execution-worker/**/*.spec.ts',
      'core/job-queue/**/*.spec.ts',
      'core/knowledge-loader/**/*.spec.ts',
      'core/observability/**/*.spec.ts',
      'core/orchestrator/**/*.spec.ts',
      'core/prompt-builder/**/*.spec.ts',
      'core/prompt-inspector/**/*.spec.ts',
      'core/preview-artifact/**/*.spec.ts',
      'core/preview-runner/**/*.spec.ts',
      'core/response-validator/**/*.spec.ts',
      'shared/**/*.spec.ts',
      'prisma/**/*.spec.ts',
    ],
    exclude: ['core/ai-provider/**/*.live.spec.ts'],
    coverage: {
      provider: 'v8',
      include: [
        'agents/code-generator/**/*.ts',
        'agents/developer/**/*.ts',
        'agents/product-owner/**/*.ts',
        'agents/qa/**/*.ts',
        'core/adaptive-orchestrator/**/*.ts',
        'core/agent-runner/**/*.ts',
        'core/ai-provider/**/*.ts',
        'core/artifact-generator/**/*.ts',
        'core/agent-contract-invariants/**/*.ts',
        'core/controlled-workspace/**/*.ts',
        'core/factory-execution-profile/**/*.ts',
        'core/sandbox-runner/**/*.ts',
        'core/factory-pipeline/**/*.ts',
        'core/execution-engine/**/*.ts',
        'core/execution-repository/**/*.ts',
        'core/execution-worker/**/*.ts',
        'core/job-queue/**/*.ts',
        'core/knowledge-loader/**/*.ts',
        'core/observability/**/*.ts',
        'core/orchestrator/**/*.ts',
        'core/prompt-builder/**/*.ts',
        'core/prompt-inspector/**/*.ts',
        'core/preview-artifact/**/*.ts',
        'core/preview-runner/**/*.ts',
        'core/response-validator/**/*.ts',
        'shared/**/*.ts',
        'prisma/**/*.ts',
      ],
      exclude: [
        '**/*.spec.ts',
        'agents/code-generator/testing/**',
        'agents/developer/testing/**',
        'agents/product-owner/testing/**',
        'agents/qa/testing/**',
        'core/orchestrator/testing/**',
        'core/execution-engine/testing/**',
        'core/execution-repository/testing/**',
        'core/execution-worker/testing/**',
        'core/controlled-workspace/testing/**',
        'core/sandbox-runner/testing/**',
        'core/sandbox-runner/integration/**',
        'core/factory-pipeline/testing/**',
        'core/factory-pipeline/integration/**',
        'core/job-queue/testing/**',
        'core/observability/testing/**',
        'core/preview-artifact/testing/**',
        'core/preview-runner/testing/**',
        'core/preview-runner/integration/**',
        'shared/types/**',
        'generated/**',
      ],
      reporter: ['text', 'json-summary'],
    },
  },
});
