export const HTTP_API_VERSION = '3.0.0';
export const MAX_EXECUTION_PAYLOAD_BYTES = 512 * 1024;
export const MAX_AUTHENTICATION_PAYLOAD_BYTES = 8 * 1024;

export const API_ENDPOINTS = Object.freeze({
  HEALTH: '/api/health',
  EXECUTIONS: '/api/executions',
  EXECUTION_BY_ID: '/api/executions/[id]',
  EXECUTION_TIMELINE: '/api/executions/[id]/timeline',
  JOB_BY_ID: '/api/jobs/[id]',
  AUTH_LOGIN: '/api/auth/login',
  AUTH_LOGOUT: '/api/auth/logout',
});

export const API_ERROR_CODES = Object.freeze({
  INVALID_JSON: 'API_INVALID_JSON',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  UNSUPPORTED_CONTENT_ENCODING: 'UNSUPPORTED_CONTENT_ENCODING',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  AUTHENTICATION_INVALID_CREDENTIALS: 'AUTHENTICATION_INVALID_CREDENTIALS',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',
  AUTHENTICATION_UNAVAILABLE: 'AUTHENTICATION_UNAVAILABLE',
  CSRF_REJECTED: 'CSRF_REJECTED',
  EXECUTION_NOT_FOUND: 'EXECUTION_NOT_FOUND',
  EXECUTION_TIMELINE_NOT_FOUND: 'EXECUTION_TIMELINE_NOT_FOUND',
  EXECUTION_REPOSITORY_UNAVAILABLE: 'EXECUTION_REPOSITORY_UNAVAILABLE',
  EXECUTION_DISPATCHER_UNAVAILABLE: 'EXECUTION_DISPATCHER_UNAVAILABLE',
  EXECUTION_DISPATCH_CONTRACT_VIOLATION: 'EXECUTION_DISPATCH_CONTRACT_VIOLATION',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
