export const HTTP_API_VERSION = '3.2.0';
export const MAX_EXECUTION_PAYLOAD_BYTES = 512 * 1024;
export const MAX_AUTHENTICATION_PAYLOAD_BYTES = 8 * 1024;
export const MAX_PLAYGROUND_PREVIEW_PAYLOAD_BYTES = 512 * 1024;
export const MAX_PLAYGROUND_VALIDATION_PAYLOAD_BYTES = 2 * 1024 * 1024;
export const MAX_PREVIEW_PAYLOAD_BYTES = 1024;

export const API_ENDPOINTS = Object.freeze({
  HEALTH: '/api/health',
  EXECUTIONS: '/api/executions',
  EXECUTION_BY_ID: '/api/executions/[id]',
  EXECUTION_TIMELINE: '/api/executions/[id]/timeline',
  JOB_BY_ID: '/api/jobs/[id]',
  AUTH_LOGIN: '/api/auth/login',
  AUTH_LOGOUT: '/api/auth/logout',
  PLAYGROUND_AGENTS: '/api/playground/agents',
  PLAYGROUND_PREVIEW: '/api/playground/preview',
  PLAYGROUND_VALIDATE: '/api/playground/validate',
  EXECUTION_PREVIEW: '/api/executions/[id]/preview',
  PREVIEW_BY_ID: '/api/previews/[id]',
});

export const API_ERROR_CODES = Object.freeze({
  INVALID_JSON: 'API_INVALID_JSON',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  UNSUPPORTED_CONTENT_ENCODING: 'UNSUPPORTED_CONTENT_ENCODING',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  AUTHENTICATION_INVALID_CREDENTIALS: 'AUTHENTICATION_INVALID_CREDENTIALS',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',
  AUTHENTICATION_UNAVAILABLE: 'AUTHENTICATION_UNAVAILABLE',
  CSRF_REJECTED: 'CSRF_REJECTED',
  EXECUTION_NOT_FOUND: 'EXECUTION_NOT_FOUND',
  EXECUTION_TIMELINE_NOT_FOUND: 'EXECUTION_TIMELINE_NOT_FOUND',
  EXECUTION_REPOSITORY_UNAVAILABLE: 'EXECUTION_REPOSITORY_UNAVAILABLE',
  EXECUTION_DISPATCHER_UNAVAILABLE: 'EXECUTION_DISPATCHER_UNAVAILABLE',
  EXECUTION_DISPATCH_CONTRACT_VIOLATION: 'EXECUTION_DISPATCH_CONTRACT_VIOLATION',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  PLAYGROUND_INSPECTION_FAILED: 'PLAYGROUND_INSPECTION_FAILED',
  PLAYGROUND_UNAVAILABLE: 'PLAYGROUND_UNAVAILABLE',
  PREVIEW_NOT_FOUND: 'PREVIEW_NOT_FOUND',
  PREVIEW_NOT_ALLOWED: 'PREVIEW_NOT_ALLOWED',
  PREVIEW_FACTORY_NOT_SUCCESS: 'PREVIEW_FACTORY_NOT_SUCCESS',
  PREVIEW_ARTIFACT_UNAVAILABLE: 'PREVIEW_ARTIFACT_UNAVAILABLE',
  PREVIEW_PROFILE_UNSUPPORTED: 'PREVIEW_PROFILE_UNSUPPORTED',
  PREVIEW_POLICY_MISMATCH: 'PREVIEW_POLICY_MISMATCH',
  PREVIEW_CONFIGURATION_INVALID: 'PREVIEW_CONFIGURATION_INVALID',
  PREVIEW_CAPACITY_EXCEEDED: 'PREVIEW_CAPACITY_EXCEEDED',
  PREVIEW_RUNTIME_UNAVAILABLE: 'PREVIEW_RUNTIME_UNAVAILABLE',
  PREVIEW_IMAGE_VERIFICATION_FAILED: 'PREVIEW_IMAGE_VERIFICATION_FAILED',
  PREVIEW_START_FAILED: 'PREVIEW_START_FAILED',
  PREVIEW_START_TIMEOUT: 'PREVIEW_START_TIMEOUT',
  PREVIEW_HEALTHCHECK_FAILED: 'PREVIEW_HEALTHCHECK_FAILED',
  PREVIEW_RUNTIME_LOST: 'PREVIEW_RUNTIME_LOST',
  PREVIEW_STOP_FAILED: 'PREVIEW_STOP_FAILED',
  PREVIEW_CLEANUP_FAILED: 'PREVIEW_CLEANUP_FAILED',
  PREVIEW_CONFLICT: 'PREVIEW_CONFLICT',
  REQUEST_ABORTED: 'REQUEST_ABORTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
