export const HTTP_API_VERSION = '1.0.0';
export const MAX_EXECUTION_PAYLOAD_BYTES = 512 * 1024;

export const API_ENDPOINTS = Object.freeze({
  HEALTH: '/api/health',
  EXECUTIONS: '/api/executions',
  EXECUTION_BY_ID: '/api/executions/[id]',
});

export const API_ERROR_CODES = Object.freeze({
  INVALID_JSON: 'API_INVALID_JSON',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  UNSUPPORTED_CONTENT_ENCODING: 'UNSUPPORTED_CONTENT_ENCODING',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  EXECUTION_LOOKUP_NOT_SUPPORTED: 'EXECUTION_LOOKUP_NOT_SUPPORTED',
  EXECUTION_CANCELLED: 'EXECUTION_CANCELLED',
  EXECUTION_ENGINE_UNAVAILABLE: 'EXECUTION_ENGINE_UNAVAILABLE',
  EXECUTION_ENGINE_FAILED: 'EXECUTION_ENGINE_FAILED',
  EXECUTION_CONTRACT_VIOLATION: 'EXECUTION_CONTRACT_VIOLATION',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
