import type {
  ExecutionHistoryDetail,
  ExecutionHistoryFactoryResult,
  ExecutionHistoryPage,
  ExecutionHistoryTimeline,
} from '@/api/execution-history-contracts';

export const HISTORY_EXECUTION_ID = `execution-${'a'.repeat(32)}`;
const HASH = '1'.repeat(64);
const KNOWLEDGE_HASH = `sha256:${'2'.repeat(64)}`;

export function historyFactoryResult(
  overrides: Partial<ExecutionHistoryFactoryResult> = {},
): ExecutionHistoryFactoryResult {
  const stageIds = [
    'PRODUCT_OWNER',
    'DEVELOPER',
    'QA',
    'CODE_GENERATOR',
    'CODE_PROFILE_VALIDATION',
    'WORKSPACE_PLAN',
    'WORKSPACE_MATERIALIZATION',
    'SANDBOX_PREPARE',
    'SANDBOX_TYPECHECK',
    'SANDBOX_BUILD',
    'SANDBOX_TEST',
    'WORKSPACE_RELEASE',
  ] as const;
  const factoryResultHash = '3'.repeat(64);
  return {
    factoryVersion: '1.0.0',
    contractVersion: '1.0.0',
    status: 'SUCCESS',
    terminalStage: 'WORKSPACE_RELEASE',
    startedAt: '2026-08-07T10:00:00.000Z',
    finishedAt: '2026-08-07T10:00:01.000Z',
    durationMs: 1_000,
    readiness: 'READY',
    generationStatus: 'SUCCESS',
    generatedFileCount: 3,
    generatedTotalBytes: 1_024,
    workspaceId: `workspace-${'4'.repeat(32)}`,
    workspaceFileCount: 3,
    workspaceTotalBytes: 1_024,
    workspaceReleaseStatus: 'RELEASED',
    sandboxStatus: 'SUCCESS',
    sandboxRunId: `sandbox-${'5'.repeat(32)}`,
    sandboxResourceOutcome: 'NONE',
    hashes: {
      lineageHash: '4'.repeat(64),
      provenanceHash: '5'.repeat(64),
      factoryResultHash,
    },
    failure: null,
    stages: stageIds.map((stageId) => ({
      stageId,
      status: 'SUCCESS',
      startedAt: '2026-08-07T10:00:00.000Z',
      finishedAt: '2026-08-07T10:00:00.010Z',
      durationMs: 10,
      outputHash: '6'.repeat(64),
      failureCode: null,
      reasonCode: null,
      profileRuleId: null,
      diagnosticSummary: null,
      resourceOutcome: stageId.startsWith('SANDBOX_') ? 'NONE' : null,
    })),
    lineage: {
      productOwnerSpecificationHash: KNOWLEDGE_HASH,
      technicalSpecificationHash: KNOWLEDGE_HASH,
      qaSpecificationHash: KNOWLEDGE_HASH,
      executionHash: HASH,
      workflowHash: HASH,
      generationHash: HASH,
      bundleHash: HASH,
      bundleContentHash: HASH,
      workspacePlanHash: HASH,
      workspaceHash: HASH,
      sandboxRequestHash: HASH,
      sandboxResultHash: HASH,
      executionProfileHash: HASH,
      generationProjectionHash: HASH,
      profileValidationHash: HASH,
      factoryResultHash,
    },
    provenance: {
      codeGeneratorAgentVersion: '1.0.0',
      codeGeneratorContractVersion: '1.0.0',
      codeGeneratorAssetBundleHash: HASH,
      executionProfileId: 'NODE_WEB_PREVIEW_24_V1',
      executionProfileVersion: '1.0.0',
      executionProfileContractVersion: '1.0.0',
      executionProfileHash: HASH,
      generationProjectionHash: HASH,
      profileValidationHash: HASH,
      workspaceVersion: '1.0.0',
      workspaceContractVersion: '1.0.0',
      workspacePolicyHash: HASH,
      workspaceConfigurationHash: HASH,
      sandboxRunnerVersion: '1.0.0',
      sandboxContractVersion: '1.0.0',
      sandboxSanitizerVersion: '1.0.0',
      sandboxHelperAbiVersion: '1.0.0',
      sandboxDependencySnapshotHash: HASH,
      sandboxPolicyId: 'NODE_TYPESCRIPT_24_V1',
      sandboxPolicyVersion: '1.0.0',
      sandboxPolicyHash: HASH,
      sandboxCommandPolicyHash: HASH,
      sandboxLimitsHash: HASH,
      sandboxAdapter: 'DOCKER',
      sandboxImageDigest: KNOWLEDGE_HASH,
      sandboxImageId: 'sha256:factory-image-id',
      sandboxPlatform: 'linux/arm64',
      sandboxRuntimeName: 'node',
      sandboxRuntimeVersion: '24.19.0',
      toolchainVersions: { node: '24.19.0', typescript: '6.0.3' },
    },
    ...overrides,
  };
}

export function historyPage(overrides: Partial<ExecutionHistoryPage> = {}): ExecutionHistoryPage {
  return {
    items: [
      {
        executionId: HISTORY_EXECUTION_ID,
        workflowId: 'workflow-001',
        projectName: 'Customer Portal',
        status: 'SUCCESS',
        readiness: 'READY',
        startedAt: '2026-08-07T10:00:00.000Z',
        finishedAt: '2026-08-07T10:00:00.250Z',
        durationMs: 250,
      },
    ],
    nextCursor: null,
    ...overrides,
  };
}

export function historyDetail(
  overrides: Partial<ExecutionHistoryDetail> = {},
): ExecutionHistoryDetail {
  return {
    ...historyPage().items[0]!,
    executionId: HISTORY_EXECUTION_ID,
    createdAt: '2026-08-07T09:59:59.999Z',
    requestId: 'request-001',
    metadata: { engineVersion: '1.0.0', contractVersion: '1.0.0', attempt: 1 },
    job: {
      jobId: `job-${'b'.repeat(32)}`,
      status: 'SUCCESS',
      queuedAt: '2026-08-07T09:59:59.000Z',
      startedAt: '2026-08-07T10:00:00.000Z',
      finishedAt: '2026-08-07T10:00:00.250Z',
    },
    hashes: {
      executionRequestHash: HASH,
      workflowRequestHash: HASH,
      workflowHash: HASH,
      lineageHash: HASH,
      provenanceHash: HASH,
      executionHash: HASH,
    },
    lineage: {
      outputs: {
        productOwnerSpecificationHash: KNOWLEDGE_HASH,
        technicalSpecificationHash: KNOWLEDGE_HASH,
        qaSpecificationHash: KNOWLEDGE_HASH,
      },
      handoffs: [
        {
          from: 'PRODUCT_OWNER',
          to: 'DEVELOPER',
          specification: 'PRODUCT_OWNER_SPECIFICATION',
          verified: true,
        },
      ],
    },
    provenance: {
      stages: [
        {
          stage: 'PRODUCT_OWNER',
          agentVersion: '1.0.1',
          outcome: 'GENERATED',
          readiness: 'READY',
          readinessDecision: {
            version: '1.0.0',
            readiness: 'READY',
            decisiveFactors: [
              { sourceStage: 'PRODUCT_OWNER', code: 'NO_LOCAL_READINESS_CONCERNS' },
            ],
          },
          hashes: {
            assetBundleHash: HASH,
            knowledgeContextHash: KNOWLEDGE_HASH,
            promptHash: HASH,
            responseHash: HASH,
            validationHash: HASH,
            generationHash: HASH,
            artifactHashes: [HASH],
          },
        },
      ],
    },
    factoryResult: null,
    ...overrides,
  };
}

export function historyTimeline(
  overrides: Partial<ExecutionHistoryTimeline> = {},
): ExecutionHistoryTimeline {
  return {
    observabilityVersion: '1.0.0',
    revision: 9,
    executionId: HISTORY_EXECUTION_ID,
    workflowId: 'workflow-001',
    requestId: 'request-001',
    status: 'SUCCESS',
    updatedAt: '2026-08-07T10:00:00.250Z',
    events: [
      {
        sequence: 1,
        type: 'execution.started',
        stageId: 'EXECUTION',
        stageName: 'Execution',
        status: 'RUNNING',
        startedAt: '2026-08-07T10:00:00.000Z',
        finishedAt: null,
        durationMs: null,
        requestId: 'request-001',
        executionId: HISTORY_EXECUTION_ID,
        errorCode: null,
      },
      {
        sequence: 2,
        type: 'execution.finished',
        stageId: 'EXECUTION',
        stageName: 'Execution',
        status: 'SUCCESS',
        startedAt: '2026-08-07T10:00:00.000Z',
        finishedAt: '2026-08-07T10:00:00.250Z',
        durationMs: 250,
        requestId: 'request-001',
        executionId: HISTORY_EXECUTION_ID,
        errorCode: null,
      },
    ],
    stages: [
      {
        stageId: 'KNOWLEDGE',
        stageName: 'Knowledge',
        status: 'SUCCESS',
        startedAt: '2026-08-07T10:00:00.000Z',
        finishedAt: '2026-08-07T10:00:00.010Z',
        durationMs: 10,
        requestId: 'request-001',
        executionId: HISTORY_EXECUTION_ID,
      },
      {
        stageId: 'PRODUCT_OWNER',
        stageName: 'Product Owner',
        status: 'SUCCESS',
        startedAt: '2026-08-07T10:00:00.010Z',
        finishedAt: '2026-08-07T10:00:00.100Z',
        durationMs: 90,
        requestId: 'request-001',
        executionId: HISTORY_EXECUTION_ID,
      },
      {
        stageId: 'DEVELOPER',
        stageName: 'Developer',
        status: 'SUCCESS',
        startedAt: '2026-08-07T10:00:00.100Z',
        finishedAt: '2026-08-07T10:00:00.200Z',
        durationMs: 100,
        requestId: 'request-001',
        executionId: HISTORY_EXECUTION_ID,
      },
      {
        stageId: 'QA',
        stageName: 'QA',
        status: 'SUCCESS',
        startedAt: '2026-08-07T10:00:00.200Z',
        finishedAt: '2026-08-07T10:00:00.250Z',
        durationMs: 50,
        requestId: 'request-001',
        executionId: HISTORY_EXECUTION_ID,
      },
    ],
    stageMetrics: ['PRODUCT_OWNER', 'DEVELOPER', 'QA'].map((stageId) => ({
      stageId: stageId as 'PRODUCT_OWNER' | 'DEVELOPER' | 'QA',
      durationMs: 10,
      promptBytes: 100,
      completionBytes: 50,
      inputTokens: 20,
      outputTokens: 10,
      totalTokens: 30,
      providerLatencyMs: 8,
      validationDurationMs: 1,
      artifactGenerationDurationMs: 1,
    })),
    summary: {
      executionId: HISTORY_EXECUTION_ID,
      workflowStatus: 'SUCCESS',
      readinessFinal: 'READY',
      totalDurationMs: 250,
      totalTokens: 90,
      totalCostEstimate: { amount: 0.001, currency: 'USD', rateCardVersion: '1.0.0' },
      executedStages: ['KNOWLEDGE', 'PRODUCT_OWNER', 'DEVELOPER', 'QA'],
      skippedStages: [],
      hashes: {
        executionRequestHash: HASH,
        workflowRequestHash: HASH,
        workflowHash: HASH,
        lineageHash: HASH,
        provenanceHash: HASH,
        executionHash: HASH,
      },
    },
    ...overrides,
  };
}
