export const PREVIEW_RUNNER_VERSION = '1.0.0';
export const PREVIEW_RUNNER_CONTRACT_VERSION = '1.0.0';
export const PREVIEW_RUNNER_HASH_ALGORITHM = 'SHA-256';
export const PREVIEW_OBSERVABILITY_CONTRACT_VERSION = '1.0.0';
