export const PREVIEW_ARTIFACT_VERSION = '1.0.0';
export const PREVIEW_ARTIFACT_CONTRACT_VERSION = '1.0.0';
export const PREVIEW_ARTIFACT_HASH_ALGORITHM = 'SHA-256';
export const PREVIEW_ARTIFACT_EXPORT_ABI_VERSION = '1.0.0';
